.# vim: ft=nroff
.TH volume 1 volume\-__0.0.1
.SH NAME
volume \- a simple wrapper around amixer for changing audio volumes
.SH SYNOPSIS
.LP
.B volume [CONTROL] [DIRECTION] [AMOUNT]
.LP
.B volume [CONTROL] on
.SH DESCRIPTION
.B volume
changes the volume of the given control.
In the first form,
.B CONTROL
is changed in 
.B DIRECTION
by 
.B AMOUNT.
In the second form,
.B CONTROL
is turned on, 
and other 
.B CONTROLs
are turned off.
(\fBMASTER\fR is turned on.)
.SH COMMANDS
.SS CONTROLS
.TP 5
.B m[aster]
This is the default.
.TP 5
.B h[eadphones]
.TP 5
.B s[peaker]
.SS DIRECTION
.TP 5
.B +
This is the default.
.TP 5
.B -
.TP 5
.B t[oggle]
.SS AMOUNT
Defaults to 5 decibels.
This option is irrelevant to toggling.
.SH EXAMPLES
.LP
.B volume h 5
increase headphone volume by 5 db.
.SH CONFIGURATION
.LP
You might want to add something like:
.IP
"volume toggle"
.IP
    XF86AudioMute
.IP
"volume -"
.IP
    XF86AudioLowerVolume
.IP
"volume +"
.IP
    XF86AudioRaiseVolume
.LP
to your 
.B "$HOME/.xbindkeys"
and add
.IP
xbindkeys
.LP
to your 
.B $HOME/.xinitrc
.SH EXIT STATUS
exits non-zero on error.
.SH AUTHOR
Noah Birnel
.SH BUGS
Probably.
.SH SEE ALSO
.TP
.BR amixer(1)
.TP
.BR xbindkeys(1)
.SH LICENSE
Copyright 2014 Noah Birnel
.sp
Do whatever you want with this software.

